DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Trips;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL
);

CREATE TABLE Trips (
	TripID INTEGER PRIMARY KEY AUTOINCREMENT,
	TripDate DATE NOT NULL,
	TripName VARCHAR(255) NOT NULL,
	Location VARCHAR(255) NOT NULL,
	Price INT CHECK (Price >= 0)
);

CREATE TABLE Bookings (
	BookingID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserID INT NOT NULL,
	TripID INT NOT NULL,
	TripDate DATE NOT NULL,
	FOREIGN KEY(UserID) REFERENCES Users(ID),
	FOREIGN KEY(TripID) REFERENCES Trips(TripID)
);
